# Во вкладке Upgrade важно соблюдать порядок ввода данных. 1 - первая эффективность, 6 - переход предмета на некст тир.
DB:
  host: 127.0.0.1
  port: 3306
  database: prison
  ssl: false # Использование SSL для БД
  username: prison
  password: password
  table: prison
Upgrade:
  WOODEN_PICKAXE:
    '1':
    - 150
    - 300
    - STONE
    - 100
    - Камня
    - COAL_ORE
    - 1
    - Угольной руды
    '2':
    - 300
    - 600
    - STONE
    - 250
    - Камня
    - COAL_ORE
    - 5
    - Угольной руды
    '3':
    - 450
    - 1800
    - STONE
    - 500
    - Камня
    - COAL_ORE
    - 10
    - Угольной руды
    '4':
    - 120
    - 300
    - STONE
    - 1200
    - Камня
    - LAPIS_ORE
    - 40
    - Лазуритной руды
    '5':
    - 500
    - 1400
    - STONE
    - 4000
    - Камня
    - LAPIS_ORE
    - 10
    - Лазуритной руды
    '6':
    - 1200
    - 1400
    - STONE
    - 4000
    - Камня
    - BRICKS
    - 25
    - Кирпичей
  STONE_PICKAXE:
    '1':
    - 2000
    - 1900
    - STONE
    - 4000
    - Камня
    - BRICKS
    - 60
    - Кирпичей
    '2':
    - 3000
    - 2500
    - STONE_BRICKS
    - 200
    - Каменных кирпичей
    - BRICKS
    - 100
    - Кирпичей
    '3':
    - 5000
    - 7200
    - STONE_BRICKS
    - 500
    - Каменных кирпичей
    - BRICKS
    - 230
    - Кирпичей
    '4':
    - 10000
    - 10000
    - STONE_BRICKS
    - 1200
    - Каменных кирпичей
    - BRICKS
    - 600
    - Кирпичей
    '5':
    - 18000
    - 20000
    - STONE_BRICKS
    - 2000
    - Каменных кирпичей
    - NETHER_QUARTZ_ORE
    - 100
    - Кварцевой руды
    '6':
    - 25000
    - 30000
    - STONE_BRICKS
    - 3200
    - Каменных кирпичей
    - NETHER_QUARTZ_ORE
    - 150
    - Кварцевой руды
  IRON_PICKAXE:
    '1':
    - 31000
    - 50000
    - STONE
    - 10000
    - Камня
    - DIAMOND_ORE
    - 250
    - Алмазной руды
    '2':
    - 50000
    - 60000
    - STONE
    - 15000
    - Камня
    - DIAMOND_ORE
    - 400
    - Алмазной руды
    '3':
    - 72100
    - 70000
    - STONE
    - 10000
    - Камня
    - DIAMOND_ORE
    - 250
    - Алмазной руды
    '4':
    - 120000
    - 100000
    - SANDSTONE
    - 20000
    - Песчанника
    - RED_SANDSTONE
    - 1000
    - Красного песчанника
    '5':
    - 320000
    - 130000
    - END_STONE
    - 20000
    - Камня края
    - PURPUR_BLOCK
    - 1500
    - Пурпурных блоков
    '6':
    - 500000
    - 200000
    - END_STONE
    - 40000
    - Камня края
    - PURPUR_BLOCK
    - 2300
    - Пурпурных блоков
  DIAMOND_PICKAXE:
    '1':
    - 550000
    - 250000
    - END_STONE
    - 60000
    - Камня края
    - PURPUR_BLOCK
    - 3000
    - Пурпурных блоков
    '2':
    - 625000
    - 300000
    - END_STONE
    - 80000
    - Камня края
    - PURPUR_BLOCK
    - 4200
    - Пурпурных блоков
    '3':
    - 700000
    - 325000
    - END_STONE
    - 90000
    - Камня края
    - OBSIDIAN
    - 1000
    - Обсидиана
    '4':
    - 900000
    - 350000
    - END_STONE
    - 115000
    - Камня края
    - OBSIDIAN
    - 2100
    - Обсидиана
    '5':
    - 1350000
    - 400000
    - END_STONE
    - 130000
    - Камня края
    - OBSIDIAN
    - 5000
    - Обсидиана
  WOODEN_SHOVEL:
    '1':
    - 250
    - 100
    - DIRT
    - 230
    - Земли
    - SAND
    - 15
    - Песка
    '2':
    - 400
    - 150
    - DIRT
    - 250
    - Земли
    - SAND
    - 50
    - Песка
    '3':
    - 700
    - 230
    - DIRT
    - 500
    - Земли
    - SAND
    - 125
    - Песка
    '4':
    - 1000
    - 4500
    - DIRT
    - 3000
    - Земли
    - SAND
    - 1000
    - Песка
    '5':
    - 10000
    - 12000
    - DIRT
    - 5000
    - Земли
    - SAND
    - 4000
    - Песка
    '6':
    - 6400
    - 1500
    - DIRT
    - 5200
    - Земли
    - SAND
    - 1200
    - Песка
  STONE_SHOVEL:
    '1':
    - 7400
    - 2000
    - DIRT
    - 6000
    - Земли
    - SAND
    - 1400
    - Песка
    '2':
    - 10000
    - 2500
    - DIRT
    - 8400
    - Земли
    - SAND
    - 1600
    - Песка
    '3':
    - 12100
    - 3200
    - DIRT
    - 500
    - Земли
    - SAND
    - 125
    - Песка
    '4':
    - 28100
    - 12300
    - DIRT
    - 3000
    - Земли
    - SAND
    - 1000
    - Песка
    '5':
    - 35000
    - 14100
    - DIRT
    - 5000
    - Земли
    - SAND
    - 4000
    - Песка
    '6':
    - 6000
    - 1500
    - DIRT
    - 5200
    - Земли
    - SAND
    - 1000
    - Песка
  IRON_SHOVEL:
    '1':
    - 10000
    - 2400
    - DIRT
    - 8000
    - Земли
    - SAND
    - 2000
    - Песка
    '2':
    - 15200
    - 2500
    - DIRT
    - 10000
    - Земли
    - SAND
    - 3000
    - Песка
    '3':
    - 52000
    - 25000
    - DIRT
    - 15400
    - Земли
    - SAND
    - 4000
    - Песка
    '4':
    - 90000
    - 32000
    - DIRT
    - 21300
    - Земли
    - SAND
    - 7000
    - Песка
    '5':
    - 120000
    - 50000
    - DIRT
    - 30000
    - Земли
    - SAND
    - 10000
    - Песка
    '6':
    - 200000
    - 70000
    - DIRT
    - 50000
    - Земли
    - SAND
    - 10000
    - Песка
  DIAMON_SHOVEL:
    '1':
    - 350000
    - 100000
    - DIRT
    - 75000
    - Земли
    - SAND
    - 18100
    - Песка
    '2':
    - 410000
    - 130000
    - DIRT
    - 100000
    - Земли
    - SAND
    - 30000
    - Песка
    '3':
    - 750000
    - 200000
    - DIRT
    - 250000
    - Земли
    - SAND
    - 70000
    - Песка
    '4':
    - 1000000
    - 250000
    - DIRT
    - 320000
    - Земли
    - SAND
    - 100000
    - Песка
    '5':
    - 1250000
    - 400000
    - DIRT
    - 500000
    - Земли
    - SAND
    - 125000
    - Песка
  LEATHER_HELMET:
    '1':
    - 10
    - SLIME
    - 10
    - Слаймов
    '2':
    - 50
    - SLIME
    - 25
    - Слаймов
    '3':
    - 120
    - SLIME
    - 50
    - Слаймов
    '4':
    - 200
    - SLIME
    - 100
    - Слаймов
    '5':
    - 400
    - SLIME
    - 200
    - Слаймов
    '6':
    - 800
    - SLIME
    - 250
    - Слаймов
  CHAINMAIL_HELMET:
    '1':
    - 1100
    - SLIME
    - 400
    - Слаймов
    '2':
    - 1600
    - SLIME
    - 600
    - Слаймов
    '3':
    - 2000
    - SLIME
    - 800
    - Слаймов
    '4':
    - 2300
    - SLIME
    - 1200
    - Слаймов
    '5':
    - 2900
    - SLIME
    - 1800
    - Слаймов
    '6':
    - 4100
    - SLIME
    - 2200
    - Слаймов
  IRON_HELMET:
    '1':
    - 5000
    - SLIME
    - 2900
    - Слаймов
    '2':
    - 7000
    - SLIME
    - 3500
    - Слаймов
    '3':
    - 12100
    - SLIME
    - 4000
    - Слаймов
    '4':
    - 15200
    - SLIME
    - 5000
    - Слаймов
    '5':
    - 21100
    - SLIME
    - 6200
    - Слаймов
    '6':
    - 35000
    - SLIME
    - 7200
    - Слаймов
  DIAMOND_HELMET:
    '1':
    - 42000
    - SLIME
    - 8500
    - Слаймов
    '2':
    - 58000
    - SLIME
    - 10000
    - Слаймов
    '3':
    - 70000
    - SLIME
    - 11500
    - Слаймов
    '4':
    - 81200
    - SLIME
    - 13500
    - Слаймов
    '5':
    - 100000
    - SLIME
    - 15000
    - Слаймов
  LEATHER_CHESTPLATE:
    '1':
    - 10
    - SLIME
    - 10
    - Слаймов
    '2':
    - 50
    - SLIME
    - 25
    - Слаймов
    '3':
    - 120
    - SLIME
    - 50
    - Слаймов
    '4':
    - 200
    - SLIME
    - 100
    - Слаймов
    '5':
    - 400
    - SLIME
    - 200
    - Слаймов
    '6':
    - 800
    - SLIME
    - 250
    - Слаймов
  CHAINMAIL_CHESTPLATE:
    '1':
    - 1100
    - SLIME
    - 400
    - Слаймов
    '2':
    - 1600
    - SLIME
    - 600
    - Слаймов
    '3':
    - 2000
    - SLIME
    - 800
    - Слаймов
    '4':
    - 2300
    - SLIME
    - 1200
    - Слаймов
    '5':
    - 2900
    - SLIME
    - 1800
    - Слаймов
    '6':
    - 4100
    - SLIME
    - 2200
    - Слаймов
  IRON_CHESTPLATE:
    '1':
    - 5000
    - SLIME
    - 2900
    - Слаймов
    '2':
    - 7000
    - SLIME
    - 3500
    - Слаймов
    '3':
    - 12100
    - SLIME
    - 4000
    - Слаймов
    '4':
    - 15200
    - SLIME
    - 5000
    - Слаймов
    '5':
    - 21100
    - SLIME
    - 6200
    - Слаймов
    '6':
    - 35000
    - SLIME
    - 7200
    - Слаймов
  DIAMOND_CHESTPLATE:
    '1':
    - 42000
    - SLIME
    - 8500
    - Слаймов
    '2':
    - 58000
    - SLIME
    - 10000
    - Слаймов
    '3':
    - 70000
    - SLIME
    - 11500
    - Слаймов
    '4':
    - 81200
    - SLIME
    - 13500
    - Слаймов
    '5':
    - 100000
    - SLIME
    - 15000
    - Слаймов
  LEATHER_LEGGINGS:
    '1':
    - 10
    - SLIME
    - 10
    - Слаймов
    '2':
    - 50
    - SLIME
    - 25
    - Слаймов
    '3':
    - 120
    - SLIME
    - 50
    - Слаймов
    '4':
    - 200
    - SLIME
    - 100
    - Слаймов
    '5':
    - 400
    - SLIME
    - 200
    - Слаймов
    '6':
    - 800
    - SLIME
    - 250
    - Слаймов
  CHAINMAIL_LEGGINGS:
    '1':
    - 1100
    - SLIME
    - 400
    - Слаймов
    '2':
    - 1600
    - SLIME
    - 600
    - Слаймов
    '3':
    - 2000
    - SLIME
    - 800
    - Слаймов
    '4':
    - 2300
    - SLIME
    - 1200
    - Слаймов
    '5':
    - 2900
    - SLIME
    - 1800
    - Слаймов
    '6':
    - 4100
    - SLIME
    - 2200
    - Слаймов
  IRON_LEGGINGS:
    '1':
    - 5000
    - SLIME
    - 2900
    - Слаймов
    '2':
    - 7000
    - SLIME
    - 3500
    - Слаймов
    '3':
    - 12100
    - SLIME
    - 4000
    - Слаймов
    '4':
    - 15200
    - SLIME
    - 5000
    - Слаймов
    '5':
    - 21100
    - SLIME
    - 6200
    - Слаймов
    '6':
    - 35000
    - SLIME
    - 7200
    - Слаймов
  DIAMOND_LEGGINGS:
    '1':
    - 42000
    - SLIME
    - 8500
    - Слаймов
    '2':
    - 58000
    - SLIME
    - 10000
    - Слаймов
    '3':
    - 70000
    - SLIME
    - 11500
    - Слаймов
    '4':
    - 81200
    - SLIME
    - 13500
    - Слаймов
    '5':
    - 100000
    - SLIME
    - 15000
    - Слаймов
  LEATHER_BOOTS:
    '1':
    - 10
    - SLIME
    - 10
    - Слаймов
    '2':
    - 50
    - SLIME
    - 25
    - Слаймов
    '3':
    - 120
    - SLIME
    - 50
    - Слаймов
    '4':
    - 200
    - SLIME
    - 100
    - Слаймов
    '5':
    - 400
    - SLIME
    - 200
    - Слаймов
    '6':
    - 800
    - SLIME
    - 250
    - Слаймов
  CHAINMAIL_BOOTS:
    '1':
    - 1100
    - SLIME
    - 400
    - Слаймов
    '2':
    - 1600
    - SLIME
    - 600
    - Слаймов
    '3':
    - 2000
    - SLIME
    - 800
    - Слаймов
    '4':
    - 2300
    - SLIME
    - 1200
    - Слаймов
    '5':
    - 2900
    - SLIME
    - 1800
    - Слаймов
    '6':
    - 4100
    - SLIME
    - 2200
    - Слаймов
  IRON_BOOTS:
    '1':
    - 5000
    - SLIME
    - 2900
    - Слаймов
    '2':
    - 7000
    - SLIME
    - 3500
    - Слаймов
    '3':
    - 12100
    - SLIME
    - 4000
    - Слаймов
    '4':
    - 15200
    - SLIME
    - 5000
    - Слаймов
    '5':
    - 21100
    - SLIME
    - 6200
    - Слаймов
    '6':
    - 35000
    - SLIME
    - 7200
    - Слаймов
  DIAMOND_BOOTS:
    '1':
    - 42000
    - SLIME
    - 8500
    - Слаймов
    '2':
    - 58000
    - SLIME
    - 10000
    - Слаймов
    '3':
    - 70000
    - SLIME
    - 11500
    - Слаймов
    '4':
    - 81200
    - SLIME
    - 13500
    - Слаймов
    '5':
    - 100000
    - SLIME
    - 15000
    - Слаймов
  WOODEN_SWORD:
    '1':
    - 150
    - SLIME
    - 10
    - Слаймов
    '2':
    - 320
    - SLIME
    - 25
    - Слаймов
    '3':
    - 460
    - SLIME
    - 50
    - Слаймов
    '4':
    - 800
    - SLIME
    - 100
    - Слаймов
    '5':
    - 2100
    - SLIME
    - 200
    - Слаймов
    '6':
    - 2500
    - SLIME
    - 250
    - Слаймов
  STONE_SWORD:
    '1':
    - 3000
    - SLIME
    - 400
    - Слаймов
    '2':
    - 3800
    - SLIME
    - 600
    - Слаймов
    '3':
    - 4000
    - SLIME
    - 800
    - Слаймов
    '4':
    - 6000
    - SLIME
    - 1200
    - Слаймов
    '5':
    - 8800
    - SLIME
    - 1800
    - Слаймов
    '6':
    - 12100
    - SLIME
    - 2200
    - Слаймов
  IRON_SWORD:
    '1':
    - 16200
    - SLIME
    - 2900
    - Слаймов
    '2':
    - 19300
    - SLIME
    - 3500
    - Слаймов
    '3':
    - 24100
    - SLIME
    - 4000
    - Слаймов
    '4':
    - 29500
    - SLIME
    - 5000
    - Слаймов
    '5':
    - 36400
    - SLIME
    - 6200
    - Слаймов
    '6':
    - 51000
    - SLIME
    - 7200
    - Слаймов
  DIAMOND_SWORD:
    '1':
    - 74000
    - SLIME
    - 8500
    - Слаймов
    '2':
    - 93000
    - SLIME
    - 10000
    - Слаймов
    '3':
    - 120000
    - SLIME
    - 11500
    - Слаймов
    '4':
    - 190000
    - SLIME
    - 13500
    - Слаймов
    '5':
    - 250000
    - SLIME
    - 15000
    - Слаймов
Normal:
  v: 2865
  type: TRIPWIRE_HOOK
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"text":"Обычный ключ"}],"text":""}'
    lore:
    - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Откройте
      этим ключём"}],"text":""}'
    - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"кейс
      на спавне."}],"text":""}'
    enchants:
      DURABILITY: 1
    ItemFlags:
    - HIDE_ENCHANTS
    internal: H4sIAAAAAAAA/+NiYOBgYM9OrQypLEhl4EjKyU/Ojs9MYQAAYbUrPBgAAAA=
Rare:
  v: 2975
  type: TRIPWIRE_HOOK
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"text":"Редкий ключ"}],"text":""}'
    lore:
    - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Откройте
      этим ключём"}],"text":""}'
    - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"кейс
      на спавне."}],"text":""}'
    enchants:
      DURABILITY: 1
    ItemFlags:
    - HIDE_ENCHANTS
    internal: H4sIAAAAAAAA/+NiYOBgYM9OrQypLEhl4MzLL8pNzInPTGEAAGeyJiYZAAAA
Heroic:
  v: 2975
  type: NETHER_STAR
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"text":"Героический ключ"}],"text":""}'
    lore:
    - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Откройте
      этим ключём"}],"text":""}'
    - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"кейс
      на спавне."}],"text":""}'
    enchants:
      DURABILITY: 1
    ItemFlags:
    - HIDE_ENCHANTS
    internal: H4sIAAAAAAAA/+NiYOBgYM9OrQypLEhl4MxILcrPTI7PTGEAACtMikcZAAAA