#Во вкладке Upgrade важно соблюдать порядок ввода данных. 1 - первая эффективность, 6 - переход предмета на некст тир.
DB:
  host: localhost
  port: 3306
  database: minecraft
  username: oreonk
  password: 123
  table: lvl
Upgrade:
  WOODEN_PICKAXE:
    1:
      - 1 #Блоки
      - 5  #Кэш(Vault)
      - "STONE" #Один из материалов
      - 1 #Количество материала выше
      - "Камня" #Перевод материала
      - "DIAMOND_BLOCK" #Один из материалов
      - 1 #Количество материала выше
      - "Алмазных блоков" #Перевод материала
    2:
      - 2
      - 10
      - "STONE"
      - 1
      - "Камня"
      - "COAL_ORE"
      - 1
      - "Угольной руды"
    3:
      - 3
      - 15
      - "STONE"
      - 1
      - "Камня"
      - "COAL_ORE"
      - 1
      - "Угольной руды"
    4:
      - 4
      - 20
      - "STONE"
      - 1
      - "Камня"
      - "COAL_ORE"
      - 1
      - "Угольной руды"
    5:
      - 5
      - 25
      - "STONE"
      - 1
      - "Камня"
      - "COAL_ORE"
      - 1
      - "Угольной руды"
    6:
      - 6
      - 30
      - "STONE"
      - 1
      - "Камня"
      - "COAL_ORE"
      - 1
      - "Угольной руды"
  STONE_PICKAXE:
    1:
      - 400
      - 40
      - "STONE"
      - 200
      - "Камня"
      - "COAL_ORE"
      - 15
      - "Угольной руды"
    2:
      - 400
      - 40
      - "STONE"
      - 200
      - "Камня"
      - "COAL_ORE"
      - 15
      - "Угольной руды"
    3:
      - 400
      - 40
      - "STONE"
      - 200
      - "Камня"
      - "COAL_ORE"
      - 15
      - "Угольной руды"
    4:
      - 400
      - 40
      - "STONE"
      - 200
      - "Камня"
      - "COAL_ORE"
      - 15
      - "Угольной руды"
    5:
      - 400
      - 40
      - "STONE"
      - 200
      - "Камня"
      - "COAL_ORE"
      - 15
      - "Угольной руды"
  LEATHER_HELMET:
    1:
      - 5 #Деньги
      - "ZOMBIE" #Какого моба убить
      - 5 #Сколько раз убить
      - "Зомби" #Перевод
      - "CHICKEN"
      - 1
      - "Курицу"
    2:
      - 10
      - "ZOMBIE"
      - 6
      - "Зомби"
      - "CHICKEN"
      - 1
      - "Курицу"
    3:
      - 15 #Деньги
      - "ZOMBIE"
      - 7
      - "Зомби"
      - "CHICKEN"
      - 1
      - "Курицу"
    4:
      - 20 #Деньги
      - "ZOMBIE"
      - 8
      - "Зомби"
      - "CHICKEN"
      - 1
      - "Курицу"
    5:
      - 25 #Деньги
      - "ZOMBIE"
      - 9
      - "Зомби"
      - "CHICKEN"
      - 1
      - "Курицу"
    6:
      - 30 #Деньги
      - "ZOMBIE"
      - 10
      - "Зомби"
      - "CHICKEN"
      - 2
      - "Курицу"
blocks:
  1:
    - "DIRT"
    - 2
  2:
    - "STONE"
    - 4
  3:
    - "GRASS"
    - 6
Lvl:
  2:
    - 500 #Блоки
    - 100 #Деньги
  3:
    - 1000
    - 175