  #Во вкладке Upgrade важно соблюдать порядок ввода данных. 1 - первая эффективность, 6 - переход предмета на некст тир.
DB:
  host: 127.0.0.1
  port: 3306
  database: oreonk_test
  ssl: false #Использование SSL для БД
  username: root
  password: Jk6kc2cv9W6LkJ@
  table: prison
Upgrade:
  WOODEN_PICKAXE:
    1:
      - 10 #Блоки
      - 30  #Кэш(Vault)
      - "STONE" #Один из материалов
      - 100 #Количество материала выше
      - "Камня" #Перевод материала
      - "COAL_ORE" #Один из материалов
      - 1 #Количество материала выше
      - "Угольной руды" #Перевод материала
    2:
      - 25
      - 60
      - "STONE"
      - 250
      - "Камня"
      - "COAL_ORE"
      - 5
      - "Угольной руды"
    3:
      - 45
      - 100
      - "STONE"
      - 500
      - "Камня"
      - "COAL_ORE"
      - 10
      - "Угольной руды"
    4:
      - 120
      - 300
      - "STONE"
      - 1200
      - "Камня"
      - "LAPIS_ORE"
      - 40
      - "Лазуритной руды"
    5:
      - 500
      - 1400
      - "STONE"
      - 4000
      - "Камня"
      - "LAPIS_ORE"
      - 10
      - "Лазуритной руды"
  STONE_PICKAXE:
    1:
      - 2000
      - 1900
      - "STONE"
      - 4000
      - "Камня"
      - "BRICKS"
      - 60
      - "Кирпичей"
    2:
      - 3000
      - 2500
      - "STONE_BRICKS"
      - 200
      - "Каменных кирпичей"
      - "BRICKS"
      - 100
      - "Кирпичей"
    3:
      - 5000
      - 7200
      - "STONE_BRICKS"
      - 500
      - "Каменных кирпичей"
      - "BRICKS"
      - 230
      - "Кирпичей"
    4:
      - 10000
      - 10000
      - "STONE_BRICKS"
      - 1200
      - "Каменных кирпичей"
      - "BRICKS"
      - 600
      - "Кирпичей"
    5:
      - 18000
      - 20000
      - "STONE_BRICKS"
      - 2000
      - "Каменных кирпичей"
      - "NETHER_QUARTZ_ORE"
      - 100
      - "Кварцевой руды"
  LEATHER_HELMET:
    1:
      - 10 #Деньги
      - "ZOMBIE" #Какого моба убить
      - 0 #Сколько раз убить
      - "Зомби" #Перевод
    2:
      - 50
      - "ZOMBIE"
      - 0
      - "Зомби"
    3:
      - 120
      - "ZOMBIE"
      - 0
      - "Зомби"
    4:
      - 200
      - "ZOMBIE"
      - 0
      - "Зомби"
    5:
      - 400 #Деньги
      - "ZOMBIE"
      - 0
      - "Зомби"
  LEATHER_CHESTPLATE:
    1:
      - 10 #Деньги
      - "ZOMBIE" #Какого моба убить
      - 0 #Сколько раз убить
      - "Зомби" #Перевод
    2:
      - 50
      - "ZOMBIE"
      - 0
      - "Зомби"
    3:
      - 120
      - "ZOMBIE"
      - 0
      - "Зомби"
    4:
      - 200
      - "ZOMBIE"
      - 0
      - "Зомби"
    5:
      - 400 #Деньги
      - "ZOMBIE"
      - 0
      - "Зомби"
  LEATHER_LEGGINGS:
    1:
      - 10 #Деньги
      - "ZOMBIE" #Какого моба убить
      - 0 #Сколько раз убить
      - "Зомби" #Перевод
    2:
      - 50
      - "ZOMBIE"
      - 0
      - "Зомби"
    3:
      - 120
      - "ZOMBIE"
      - 0
      - "Зомби"
    4:
      - 200
      - "ZOMBIE"
      - 0
      - "Зомби"
    5:
      - 400 #Деньги
      - "ZOMBIE"
      - 0
      - "Зомби"
  LEATHER_BOOTS:
    1:
      - 10 #Деньги
      - "ZOMBIE" #Какого моба убить
      - 0 #Сколько раз убить
      - "Зомби" #Перевод
    2:
      - 50
      - "ZOMBIE"
      - 0
      - "Зомби"
    3:
      - 120
      - "ZOMBIE"
      - 0
      - "Зомби"
    4:
      - 200
      - "ZOMBIE"
      - 0
      - "Зомби"
    5:
      - 400 #Деньги
      - "ZOMBIE"
      - 0
      - "Зомби"
  WOODEN_SWORD:
    1:
      - 10 #Деньги
      - "ZOMBIE" #Какого моба убить
      - 0 #Сколько раз убить
      - "Зомби" #Перевод
    2:
      - 50
      - "ZOMBIE"
      - 0
      - "Зомби"
    3:
      - 120
      - "ZOMBIE"
      - 0
      - "Зомби"
    4:
      - 200
      - "ZOMBIE"
      - 0
      - "Зомби"
    5:
      - 400 #Деньги
      - "ZOMBIE"
      - 0
      - "Зомби"
  WOODEN_SHOVEL:
    1:
      - 10 #Блоки
      - 30  #Кэш(Vault)
      - "DIRT" #Один из материалов
      - 100 #Количество материала выше
      - "Земли" #Перевод материала
      - "SAND" #Один из материалов
      - 1 #Количество материала выше
      - "Песка" #Перевод материала
    2:
      - 25
      - 60
      - "DIRT"
      - 250
      - "Земли"
      - "SAND"
      - 5
      - "Песка"
    3:
      - 45
      - 100
      - "DIRT"
      - 500
      - "Земли"
      - "SAND"
      - 15
      - "Песка"
    4:
      - 120
      - 300
      - "DIRT"
      - 1200
      - "Земли"
      - "SAND"
      - 24
      - "Песка"
    5:
      - 500
      - 1400
      - "DIRT"
      - 4000
      - "Земли"
      - "SAND"
      - 50
      - "Песка"

