main: com.oreonk.TestPlug
name: Prison
version: 1
depend: [Vault, PlaceholderAPI, GemsEconomy, LuckPerms]
api-version: 1.17
permissions:
  prison.autosell:
    description: Перм для возможности переключения автоселла.
  prison.autosell.on:
    description: Включить автоселл
  prison.autosell.off:
    description: Отключить автоселл
commands:
  shop:
    description: "Открывает донат магазин"
    usage: /shop
    permission: default
  thx:
    description: "Отблагодарить игрока за бустер"
    usage: /thx
    permission: default
  autosell:
    description: "Включение/отключение автоселла"
    usage: /autosell <on:off>
  lvl:
    description: "Повышение уровня"
    usage: /lvl