main: com.oreonk.Prison
name: Prison
version: 1
depend: [Vault, PlaceholderAPI]
api-version: 1.17
permissions:
  prison.autosell:
    description: Перм для возможности переключения автоселла.
  prison.autosell.on:
    description: Включить автоселл
  prison.autosell.off:
    description: Отключить автоселл
commands:
  shop:
    description: "Открывает донат магазин"
    usage: /shop
    permission: default
    aliases: donate
  thx:
    description: "Отблагодарить игрока за бустер"
    usage: /thx
    permission: default
  autosell:
    description: "Включение/отключение автоселла"
    usage: /autosell <on:off>
    aliases: as
  lvl:
    description: "Повышение уровня"
    usage: /lvl
    aliases: level
  upgrade:
    description: "Улучшение вещей"
    usage: /upgrade
    aliases: u
  faction:
    description: "Выбор фракции"
    usage: /faction
  base:
    description: "Телепортация на базу лоакции"
    usage: /base
  rubbish:
    description: "Мусорка"
    usage: /rubbish
    aliases: rubb
  hide:
    description: "Спрятать игроков"
    usage: /hide <on:off>
  adminbooster:
    description: "Админ бустер блоков на 2 дня"
    usage: /adminbooster
    permission: prison.admin.adminbooster
  test:
    usage: /prisontest
    permission: prison.test.test
  mine:
    usage: /mine *номер шахты*
  spawn:
    usage: /spawn
  localboost:
    usage: /localboost [player minutes multiplier]
    permission: prison.admin.localboost
  adminLvl:
    usage: /adminlvl [player lvl]
    permission: prison.admin.adminlvl
  statWipe:
    usage: /statwipe [player]
    permission: prison.admin.statwipe
  cell:
    usage: /cell
  pay:
    usage: /pay [игрок количество]
    permission: default
  achievements:
    usage: /achievements
    permission: default
  adminmoney:
    usage: /adminmoney [игрок количество]
    permission: prison.admin.adminmoney
  balance:
    usage: /balance | /money
    permission: default
    aliases: money
  plml:
    usage: /plml [player multiplier]
    permission: prison.admin.localboost
  localblockboost:
    usage: /localblockboost [player minutes multiplier]
    permission: prison.admin.localboost
  admintakemoney:
    usage: /admintakemoney [player amount]
    permission: prison.admin.adminmoney
  admincommissionadd:
    usage: /admincommissionadd [player <1/2>]
    permission: prison.admin.adminmoney
  localmobboost:
    usage: /localmobboost [player minutes multiplier]
    permission: prison.admin.localboost
  menu:
    usage: /menu
    permission: default
  moneylvlpercent:
    usage: /moneylvlpercent player *percent*
    permission: prison.admin.adminmoney
  givestars:
    usage: /givestars player *amount*
    permission: prison.admin.givestars


